SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, (SELECT ROUND(AVG(REVIEW_SCORE), 2) FROM REST_REVIEW WHERE I.REST_ID = REST_ID) AS SCORE
FROM REST_INFO I
WHERE ADDRESS LIKE '서울%' AND (SELECT ROUND(AVG(REVIEW_SCORE), 2) FROM REST_REVIEW WHERE I.REST_ID = REST_ID) != 0
ORDER BY SCORE DESC, FAVORITES DESC