SELECT AUTHOR_ID, (SELECT AUTHOR_NAME FROM AUTHOR WHERE NEW_TABLE.AUTHOR_ID = AUTHOR_ID) AS AUTHOR_NAME, CATEGORY, SUM(CATEGORY_PRICE) AS TOTAL_SALES 
FROM (SELECT author_id, category, price * SALES AS CATEGORY_PRICE
FROM BOOK_SALES A
JOIN BOOK B
ON A.BOOK_ID = B.BOOK_ID
WHERE MONTH(A.SALES_DATE) = 1 AND YEAR(A.SALES_DATE) = 2022) AS NEW_TABLE
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC