SELECT COUNT(*) AS USERS 
FROM USER_INFO
GROUP BY AGE
HAVING AGE IS NULL;

SELECT COUNT(*) AS USERS
FROM USER_INFO
WHERE AGE IS NULL;

SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE FROM FOOD_PRODUCT
WHERE PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT)