-- 서브쿼리를 이용한 풀이
SELECT FLAVOR FROM FIRST_HALF 
WHERE TOTAL_ORDER >= 3000 AND 
FLAVOR IN (SELECT FLAVOR FROM ICECREAM_INFO WHERE INGREDIENT_TYPE = "fruit_based") 
ORDER BY TOTAL_ORDER DESC;

-- JOIN을 이용한 풀이
SELECT A.FLAVOR FROM FIRST_HALF A
JOIN ICECREAM_INFO B
ON A.FLAVOR = B.FLAVOR
WHERE B.INGREDIENT_TYPE = "fruit_based" AND
A.TOTAL_ORDER >= 3000;